name = "LWBGT"
uuid = "6179963f-d197-4f12-88b2-ca124f9228fe"
authors = ["Yifei Zheng <zyf0717@gmail.com>"]
version = "0.1.0"

[deps]
lwbgt_jll = "cf665c29-16db-5973-80e9-eb7e043c22cf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
Test = "1"
julia = "1.10"
lwbgt_jll = "1.1.0"
